/** Database canzoni del gioco (solo queste compaiono in autocomplete) */
window.SONGS = [
  // --- catalogo originale ---
  { id: '1', title: 'Call Me Maybe', artist: 'Carly Rae Jepsen', searchQuery: 'Call Me Maybe Carly Rae Jepsen' },
  { id: '2', title: 'Pompeii', artist: 'Bastille', searchQuery: 'Pompeii Bastille' },
  { id: '3', title: 'Hey Brother', artist: 'Avicii', searchQuery: 'Hey Brother Avicii' },
  { id: '4', title: 'California Gurls', artist: 'Katy Perry', searchQuery: 'California Gurls Katy Perry' },
  { id: '5', title: 'Tik Tok', artist: 'Kesha', searchQuery: 'Tik Tok Kesha' },
  { id: '6', title: 'Party Rock Anthem', artist: 'LMFAO', searchQuery: 'Party Rock Anthem LMFAO' },
  { id: '7', title: 'Payphone', artist: 'Maroon 5', searchQuery: 'Payphone Maroon 5' },
  { id: '8', title: 'Whistle', artist: 'Flo Rida', searchQuery: 'Whistle Flo Rida' },
  { id: '9', title: 'Waka Waka', artist: 'Shakira', searchQuery: 'Waka Waka Shakira' },
  { id: '10', title: 'Replay', artist: 'Iyaz', searchQuery: 'Replay Iyaz' },
  { id: '11', title: 'Timber', artist: 'Pitbull', searchQuery: 'Timber Pitbull Kesha' },
  { id: '12', title: 'Balada', artist: 'Gusttavo Lima', searchQuery: 'Balada Gusttavo Lima' },
  { id: '13', title: 'Right Round', artist: 'Flo Rida', searchQuery: 'Right Round Flo Rida' },
  { id: '14', title: 'Die Young', artist: 'Kesha', searchQuery: 'Die Young Kesha' },
  { id: '15', title: 'Danza Kuduro', artist: 'Don Omar', searchQuery: 'Danza Kuduro Don Omar Lucenzo' },
  { id: '16', title: 'Stereo Hearts', artist: 'Gym Class Heroes', searchQuery: 'Stereo Hearts Gym Class Heroes' },
  { id: '17', title: 'Moves Like Jagger', artist: 'Maroon 5', searchQuery: 'Moves Like Jagger Maroon 5' },
  { id: '18', title: 'Hangover', artist: 'Taio Cruz ft. Flo Rida', searchQuery: 'Hangover Taio Cruz Flo Rida' },
  { id: '19', title: 'Dynamite', artist: 'Taio Cruz', searchQuery: 'Dynamite Taio Cruz' },
  { id: '20', title: 'Levels', artist: 'Avicii', searchQuery: 'Levels Avicii' },
  { id: '21', title: 'Wake Me Up', artist: 'Avicii', searchQuery: 'Wake Me Up Avicii' },
  { id: '22', title: 'Ma Cherie', artist: 'DJ Antoine', searchQuery: 'Ma Cherie DJ Antoine' },
  { id: '23', title: 'In Da Club', artist: '50 Cent', searchQuery: 'In Da Club 50 Cent' },
  { id: '24', title: 'Memories', artist: 'David Guetta', searchQuery: 'Memories David Guetta Kid Cudi' },
  { id: '25', title: 'What Makes You Beautiful', artist: 'One Direction', searchQuery: 'What Makes You Beautiful One Direction' },
  { id: '26', title: "C'est la vie", artist: 'Khaled', searchQuery: "C'est la vie Khaled" },
  { id: '27', title: 'Papaoutai', artist: 'Stromae', searchQuery: 'Papaoutai Stromae' },
  { id: '28', title: 'Limbo', artist: 'Daddy Yankee', searchQuery: 'Limbo Daddy Yankee' },
  { id: '29', title: 'The Fate of Ophelia', artist: 'Taylor Swift', searchQuery: 'The Fate of Ophelia Taylor Swift' },
  { id: '30', title: 'NUEVAYoL', artist: 'Bad Bunny', searchQuery: 'NUEVAYoL Bad Bunny' },
  { id: '31', title: 'Gata Only', artist: 'FloyyMenor', searchQuery: 'Gata Only FloyyMenor' },
  { id: '32', title: 'Lemonade', artist: 'Internet Money', searchQuery: 'Lemonade Internet Money Don Toliver' },
  { id: '33', title: 'Mood', artist: '24kGoldn', searchQuery: 'Mood 24kGoldn' },
  { id: '34', title: 'Charger', artist: 'ELIO', searchQuery: 'CHARGER ELIO' },
  { id: '35', title: "I Don't Care", artist: 'Ed Sheeran & Justin Bieber', searchQuery: "I Don't Care Ed Sheeran Justin Bieber" },
  { id: '36', title: 'Giovani Re', artist: 'Sfera Ebbasta', searchQuery: 'Giovani Re Sfera Ebbasta' },
  { id: '37', title: 'Good Times', artist: 'Ghali', searchQuery: 'Good Times Ghali' },
  { id: '38', title: 'Autostop', artist: 'Shade', searchQuery: 'Autostop Shade' },
  { id: '39', title: 'Dove e quando', artist: 'Benji & Fede', searchQuery: 'Dove e quando Benji Fede' },
  { id: '40', title: 'Ostia Lido', artist: 'J-Ax', searchQuery: 'Ostia Lido J-Ax' },
  { id: '41', title: 'Senorita', artist: 'Shawn Mendes & Camila Cabello', searchQuery: 'Senorita Shawn Mendes Camila Cabello' },
  { id: '42', title: "La hit dell'estate", artist: 'Shade', searchQuery: "La hit dell'estate Shade" },

  // --- anni 2010 (pezzi mancanti) ---
  { id: '43', title: 'Rolling in the Deep', artist: 'Adele', searchQuery: 'Rolling in the Deep Adele' },
  { id: '44', title: 'Somebody That I Used to Know', artist: 'Gotye ft. Kimbra', searchQuery: 'Somebody That I Used to Know Gotye' },
  { id: '45', title: 'We Found Love', artist: 'Rihanna ft. Calvin Harris', searchQuery: 'We Found Love Rihanna Calvin Harris' },
  { id: '46', title: 'Get Lucky', artist: 'Daft Punk ft. Pharrell Williams', searchQuery: 'Get Lucky Daft Punk Pharrell' },
  { id: '47', title: 'Happy', artist: 'Pharrell Williams', searchQuery: 'Happy Pharrell Williams' },
  { id: '48', title: 'Uptown Funk', artist: 'Mark Ronson ft. Bruno Mars', searchQuery: 'Uptown Funk Mark Ronson Bruno Mars' },
  { id: '49', title: 'Thinking Out Loud', artist: 'Ed Sheeran', searchQuery: 'Thinking Out Loud Ed Sheeran' },
  { id: '50', title: 'Sugar', artist: 'Maroon 5', searchQuery: 'Sugar Maroon 5' },
  { id: '51', title: 'Cheerleader', artist: 'OMI', searchQuery: 'Cheerleader OMI' },
  { id: '52', title: 'Cake by the Ocean', artist: 'DNCE', searchQuery: 'Cake by the Ocean DNCE' },
  { id: '53', title: 'Shape of You', artist: 'Ed Sheeran', searchQuery: 'Shape of You Ed Sheeran' },
  { id: '54', title: 'Despacito', artist: 'Luis Fonsi ft. Daddy Yankee', searchQuery: 'Despacito Luis Fonsi Daddy Yankee' },
  { id: '55', title: 'Havana', artist: 'Camila Cabello ft. Young Thug', searchQuery: 'Havana Camila Cabello' },
  { id: '56', title: 'Perfect', artist: 'Ed Sheeran', searchQuery: 'Perfect Ed Sheeran' },
  { id: '57', title: 'Rolls Royce', artist: 'Achille Lauro', searchQuery: 'Rolls Royce Achille Lauro' },

  // --- 2018-2020 ---
  { id: '58', title: "God's Plan", artist: 'Drake', searchQuery: "God's Plan Drake" },
  { id: '59', title: 'Shallow', artist: 'Lady Gaga & Bradley Cooper', searchQuery: 'Shallow Lady Gaga Bradley Cooper' },
  { id: '60', title: 'Bad Guy', artist: 'Billie Eilish', searchQuery: 'bad guy Billie Eilish' },
  { id: '61', title: 'Dance Monkey', artist: 'Tones and I', searchQuery: 'Dance Monkey Tones and I' },
  { id: '62', title: 'Blinding Lights', artist: 'The Weeknd', searchQuery: 'Blinding Lights The Weeknd' },
  { id: '63', title: 'Watermelon Sugar', artist: 'Harry Styles', searchQuery: 'Watermelon Sugar Harry Styles' },
  { id: '64', title: 'Levitating', artist: 'Dua Lipa', searchQuery: 'Levitating Dua Lipa' },

  // --- 2021-2022 ---
  { id: '65', title: 'Zitti e buoni', artist: 'Maneskin', searchQuery: 'Zitti e buoni Maneskin' },
  { id: '66', title: 'Mille', artist: 'Fedez, Achille Lauro & Orietta Berti', searchQuery: 'Mille Fedez Achille Lauro Orietta Berti' },
  { id: '67', title: 'Stay', artist: 'The Kid Laroi & Justin Bieber', searchQuery: 'Stay The Kid Laroi Justin Bieber' },
  { id: '68', title: 'As It Was', artist: 'Harry Styles', searchQuery: 'As It Was Harry Styles' },
  { id: '69', title: 'Heat Waves', artist: 'Glass Animals', searchQuery: 'Heat Waves Glass Animals' },
  { id: '70', title: 'Unholy', artist: 'Sam Smith & Kim Petras', searchQuery: 'Unholy Sam Smith Kim Petras' },
  { id: '71', title: 'Sunroof', artist: 'Nicky Youre & dazy', searchQuery: 'Sunroof Nicky Youre dazy' },

  // --- 2023 ---
  { id: '72', title: 'Flowers', artist: 'Miley Cyrus', searchQuery: 'Flowers Miley Cyrus' },
  { id: '73', title: 'Last Night', artist: 'Morgan Wallen', searchQuery: 'Last Night Morgan Wallen' },
  { id: '74', title: 'Kill Bill', artist: 'SZA', searchQuery: 'Kill Bill SZA' },
  { id: '75', title: 'Calm Down', artist: 'Rema & Selena Gomez', searchQuery: 'Calm Down Rema Selena Gomez' },
  { id: '76', title: 'Cruel Summer', artist: 'Taylor Swift', searchQuery: 'Cruel Summer Taylor Swift' },
  { id: '77', title: 'Sprinter', artist: 'Dave & Central Cee', searchQuery: 'Sprinter Dave Central Cee' },
  { id: '78', title: 'La dolce vita', artist: 'Fedez, Tananai & Mara Sattei', searchQuery: 'La dolce vita Fedez Tananai Mara Sattei' },

  // --- 2024 ---
  { id: '79', title: 'Espresso', artist: 'Sabrina Carpenter', searchQuery: 'Espresso Sabrina Carpenter' },
  { id: '80', title: 'Beautiful Things', artist: 'Benson Boone', searchQuery: 'Beautiful Things Benson Boone' },
  { id: '81', title: 'Not Like Us', artist: 'Kendrick Lamar', searchQuery: 'Not Like Us Kendrick Lamar' },
  { id: '82', title: 'Birds of a Feather', artist: 'Billie Eilish', searchQuery: 'Birds of a Feather Billie Eilish' },
  { id: '83', title: 'Die With a Smile', artist: 'Lady Gaga & Bruno Mars', searchQuery: 'Die With a Smile Lady Gaga Bruno Mars' },
  { id: '84', title: 'APT.', artist: 'ROSE & Bruno Mars', searchQuery: 'APT ROSE Bruno Mars' },
  { id: '85', title: 'Sesso e Samba', artist: 'Tony Effe & Gaia', searchQuery: 'Sesso e Samba Tony Effe Gaia' },
  { id: '86', title: 'Come un tuono', artist: 'Rose Villain & Gue', searchQuery: 'Come un tuono Rose Villain Gue' },
  { id: '87', title: 'Paprika', artist: 'Ghali', searchQuery: 'Paprika Ghali' },

  // --- 2025 ---
  { id: '88', title: 'Ordinary', artist: 'Alex Warren', searchQuery: 'Ordinary Alex Warren' },
  { id: '89', title: 'Luther', artist: 'Kendrick Lamar & SZA', searchQuery: 'Luther Kendrick Lamar SZA' },
  { id: '90', title: 'Golden', artist: 'HUNTR/X', searchQuery: 'Golden HUNTR/X KPop Demon Hunters' },
  { id: '91', title: 'Messy', artist: 'Lola Young', searchQuery: 'Messy Lola Young' },
  { id: '92', title: 'back to friends', artist: 'sombr', searchQuery: 'back to friends sombr' },

  // --- 2026 ---
  { id: '93', title: 'La Testa Gira', artist: 'Fred De Palma, Anitta & Emis Killa', searchQuery: 'La Testa Gira Fred De Palma Anitta Emis Killa' },
  { id: '94', title: 'Al Mio Paese', artist: 'Serena Brancale, DELIA & Levante', searchQuery: 'Al Mio Paese Serena Brancale DELIA Levante' },
  { id: '95', title: 'Canzone Estiva', artist: 'Annalisa', searchQuery: 'Canzone Estiva Annalisa' },
  { id: '96', title: 'Cabana', artist: 'Irama', searchQuery: 'Cabana Irama' },
  { id: '97', title: 'Buon Vento', artist: 'Jovanotti & Alfa', searchQuery: 'Buon Vento Jovanotti Alfa' },
  { id: '98', title: 'Midnight Sun', artist: 'Zara Larsson', searchQuery: 'Midnight Sun Zara Larsson' },
  { id: '99', title: 'Dai Dai', artist: 'Shakira & Burna Boy', searchQuery: 'Dai Dai Shakira Burna Boy' },
]
